// Generated by Xata Codegen 0.29.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "nextauth_verificationTokens",
    columns: [
      { name: "identifier", type: "string" },
      { name: "token", type: "string" },
      { name: "expires", type: "datetime" },
    ],
  },
  {
    name: "nextauth_users",
    columns: [
      { name: "email", type: "email" },
      { name: "emailVerified", type: "datetime" },
      { name: "name", type: "string" },
      { name: "image", type: "string" },
    ],
    revLinks: [
      { column: "user", table: "favorite_barbershop" },
      { column: "user", table: "nextauth_accounts" },
      { column: "user", table: "nextauth_users_accounts" },
      { column: "user", table: "nextauth_users_sessions" },
      { column: "user", table: "nextauth_sessions" },
    ],
  },
  {
    name: "barbershop",
    columns: [
      { name: "name", type: "string" },
      { name: "phone_number", type: "string" },
      { name: "email", type: "email" },
      { name: "verified", type: "bool" },
      { name: "address", type: "link", link: { table: "address" } },
      { name: "logo", type: "file", file: { defaultPublicAccess: true } },
    ],
    revLinks: [
      { column: "barbershop", table: "favorite_barbershop" },
      { column: "barbershop", table: "price_list" },
    ],
  },
  {
    name: "address",
    columns: [
      { name: "street", type: "string" },
      { name: "house_number", type: "string" },
      { name: "zip", type: "string" },
      { name: "city", type: "string" },
    ],
    revLinks: [{ column: "address", table: "barbershop" }],
  },
  {
    name: "favorite_barbershop",
    columns: [
      { name: "barbershop", type: "link", link: { table: "barbershop" } },
      { name: "user", type: "link", link: { table: "nextauth_users" } },
    ],
  },
  {
    name: "nextauth_accounts",
    columns: [
      { name: "user", type: "link", link: { table: "nextauth_users" } },
      { name: "type", type: "string" },
      { name: "provider", type: "string" },
      { name: "providerAccountId", type: "string" },
      { name: "refresh_token", type: "string" },
      { name: "access_token", type: "string" },
      { name: "expires_at", type: "int" },
      { name: "token_type", type: "string" },
      { name: "scope", type: "string" },
      { name: "id_token", type: "text" },
      { name: "session_state", type: "string" },
    ],
    revLinks: [{ column: "account", table: "nextauth_users_accounts" }],
  },
  {
    name: "nextauth_users_accounts",
    columns: [
      { name: "user", type: "link", link: { table: "nextauth_users" } },
      { name: "account", type: "link", link: { table: "nextauth_accounts" } },
    ],
  },
  {
    name: "nextauth_users_sessions",
    columns: [
      { name: "user", type: "link", link: { table: "nextauth_users" } },
      { name: "session", type: "link", link: { table: "nextauth_sessions" } },
    ],
  },
  {
    name: "nextauth_sessions",
    columns: [
      { name: "sessionToken", type: "string" },
      { name: "expires", type: "datetime" },
      { name: "user", type: "link", link: { table: "nextauth_users" } },
    ],
    revLinks: [{ column: "session", table: "nextauth_users_sessions" }],
  },
  {
    name: "price_list",
    columns: [
      { name: "currency", type: "string" },
      { name: "barbershop", type: "link", link: { table: "barbershop" } },
    ],
    revLinks: [{ column: "price_list", table: "price_list_item" }],
  },
  {
    name: "price_list_item",
    columns: [
      { name: "name", type: "string" },
      { name: "description", type: "string" },
      { name: "price", type: "float" },
      { name: "price_list", type: "link", link: { table: "price_list" } },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type NextauthVerificationTokens =
  InferredTypes["nextauth_verificationTokens"];
export type NextauthVerificationTokensRecord = NextauthVerificationTokens &
  XataRecord;

export type NextauthUsers = InferredTypes["nextauth_users"];
export type NextauthUsersRecord = NextauthUsers & XataRecord;

export type Barbershop = InferredTypes["barbershop"];
export type BarbershopRecord = Barbershop & XataRecord;

export type Address = InferredTypes["address"];
export type AddressRecord = Address & XataRecord;

export type FavoriteBarbershop = InferredTypes["favorite_barbershop"];
export type FavoriteBarbershopRecord = FavoriteBarbershop & XataRecord;

export type NextauthAccounts = InferredTypes["nextauth_accounts"];
export type NextauthAccountsRecord = NextauthAccounts & XataRecord;

export type NextauthUsersAccounts = InferredTypes["nextauth_users_accounts"];
export type NextauthUsersAccountsRecord = NextauthUsersAccounts & XataRecord;

export type NextauthUsersSessions = InferredTypes["nextauth_users_sessions"];
export type NextauthUsersSessionsRecord = NextauthUsersSessions & XataRecord;

export type NextauthSessions = InferredTypes["nextauth_sessions"];
export type NextauthSessionsRecord = NextauthSessions & XataRecord;

export type PriceList = InferredTypes["price_list"];
export type PriceListRecord = PriceList & XataRecord;

export type PriceListItem = InferredTypes["price_list_item"];
export type PriceListItemRecord = PriceListItem & XataRecord;

export type DatabaseSchema = {
  nextauth_verificationTokens: NextauthVerificationTokensRecord;
  nextauth_users: NextauthUsersRecord;
  barbershop: BarbershopRecord;
  address: AddressRecord;
  favorite_barbershop: FavoriteBarbershopRecord;
  nextauth_accounts: NextauthAccountsRecord;
  nextauth_users_accounts: NextauthUsersAccountsRecord;
  nextauth_users_sessions: NextauthUsersSessionsRecord;
  nextauth_sessions: NextauthSessionsRecord;
  price_list: PriceListRecord;
  price_list_item: PriceListItemRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Talha-Bayansar-s-workspace-l2p3gj.eu-central-1.xata.sh/db/my-barber",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
