// Generated by Xata Codegen 0.29.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "nextauth_verificationTokens",
    columns: [
      { name: "identifier", type: "string" },
      { name: "token", type: "string" },
      { name: "expires", type: "datetime" },
    ],
  },
  {
    name: "nextauth_users",
    columns: [
      { name: "email", type: "email" },
      { name: "emailVerified", type: "datetime" },
      { name: "name", type: "string" },
      { name: "image", type: "string" },
    ],
    revLinks: [
      { column: "user", table: "favorite_barbershop" },
      { column: "user", table: "nextauth_accounts" },
      { column: "user", table: "nextauth_users_accounts" },
      { column: "user", table: "nextauth_users_sessions" },
      { column: "user", table: "nextauth_sessions" },
      { column: "user", table: "barber" },
      { column: "user", table: "reservation" },
      { column: "owner", table: "barbershop" },
      { column: "user", table: "user_preferences" },
    ],
  },
  {
    name: "barbershop",
    columns: [
      { name: "name", type: "string" },
      { name: "phone_number", type: "string" },
      { name: "email", type: "email" },
      { name: "address", type: "link", link: { table: "address" } },
      { name: "logo", type: "file", file: { defaultPublicAccess: true } },
      { name: "owner", type: "link", link: { table: "nextauth_users" } },
      { name: "verified", type: "bool", defaultValue: "false" },
    ],
    revLinks: [
      { column: "barbershop", table: "favorite_barbershop" },
      { column: "barbershop", table: "price_list" },
      { column: "barbershop", table: "opening_hours" },
      { column: "barbershop", table: "barber" },
      { column: "barbershop", table: "reservation" },
      { column: "barbershop", table: "barbershop_barber_invitation" },
      { column: "barbershop", table: "barbershop_preferences" },
    ],
  },
  {
    name: "address",
    columns: [
      { name: "street", type: "string" },
      { name: "house_number", type: "string" },
      { name: "zip", type: "string" },
      { name: "city", type: "string" },
    ],
    revLinks: [{ column: "address", table: "barbershop" }],
  },
  {
    name: "favorite_barbershop",
    columns: [
      { name: "barbershop", type: "link", link: { table: "barbershop" } },
      { name: "user", type: "link", link: { table: "nextauth_users" } },
    ],
  },
  {
    name: "nextauth_accounts",
    columns: [
      { name: "user", type: "link", link: { table: "nextauth_users" } },
      { name: "type", type: "string" },
      { name: "provider", type: "string" },
      { name: "providerAccountId", type: "string" },
      { name: "refresh_token", type: "string" },
      { name: "access_token", type: "string" },
      { name: "expires_at", type: "int" },
      { name: "token_type", type: "string" },
      { name: "scope", type: "string" },
      { name: "id_token", type: "text" },
      { name: "session_state", type: "string" },
    ],
    revLinks: [{ column: "account", table: "nextauth_users_accounts" }],
  },
  {
    name: "nextauth_users_accounts",
    columns: [
      { name: "user", type: "link", link: { table: "nextauth_users" } },
      { name: "account", type: "link", link: { table: "nextauth_accounts" } },
    ],
  },
  {
    name: "nextauth_users_sessions",
    columns: [
      { name: "user", type: "link", link: { table: "nextauth_users" } },
      { name: "session", type: "link", link: { table: "nextauth_sessions" } },
    ],
  },
  {
    name: "nextauth_sessions",
    columns: [
      { name: "sessionToken", type: "string" },
      { name: "expires", type: "datetime" },
      { name: "user", type: "link", link: { table: "nextauth_users" } },
    ],
    revLinks: [{ column: "session", table: "nextauth_users_sessions" }],
  },
  {
    name: "price_list",
    columns: [
      { name: "currency", type: "string" },
      { name: "barbershop", type: "link", link: { table: "barbershop" } },
    ],
    revLinks: [{ column: "price_list", table: "price_list_item" }],
  },
  {
    name: "price_list_item",
    columns: [
      { name: "name", type: "string" },
      { name: "description", type: "string" },
      { name: "price", type: "float" },
      { name: "price_list", type: "link", link: { table: "price_list" } },
      { name: "duration", type: "int" },
    ],
    revLinks: [{ column: "price_list_item", table: "reservation" }],
  },
  {
    name: "opening_hours",
    columns: [
      { name: "start_time", type: "int" },
      { name: "duration", type: "int" },
      { name: "day_of_week", type: "int" },
      { name: "barbershop", type: "link", link: { table: "barbershop" } },
      { name: "with_reservation", type: "bool" },
    ],
  },
  {
    name: "barber",
    columns: [
      { name: "first_name", type: "string" },
      { name: "last_name", type: "string" },
      { name: "user", type: "link", link: { table: "nextauth_users" } },
      { name: "barbershop", type: "link", link: { table: "barbershop" } },
      { name: "image", type: "file", file: { defaultPublicAccess: true } },
    ],
    revLinks: [
      { column: "barber", table: "barber_hair_type" },
      { column: "barber", table: "reservation" },
      { column: "barber", table: "barbershop_barber_invitation" },
      { column: "barber", table: "barber_skill" },
    ],
  },
  {
    name: "hair_type",
    columns: [{ name: "name", type: "string" }],
    revLinks: [
      { column: "hair_type", table: "barber_hair_type" },
      { column: "hair_type", table: "user_preferences" },
      { column: "skill", table: "barber_skill" },
    ],
  },
  {
    name: "barber_hair_type",
    columns: [
      { name: "barber", type: "link", link: { table: "barber" } },
      { name: "hair_type", type: "link", link: { table: "hair_type" } },
    ],
  },
  {
    name: "reservation",
    columns: [
      { name: "date", type: "string" },
      { name: "start_time", type: "int" },
      { name: "user", type: "link", link: { table: "nextauth_users" } },
      {
        name: "price_list_item",
        type: "link",
        link: { table: "price_list_item" },
      },
      { name: "barber", type: "link", link: { table: "barber" } },
      { name: "barbershop", type: "link", link: { table: "barbershop" } },
      { name: "is_paid", type: "bool" },
    ],
  },
  {
    name: "barbershop_barber_invitation",
    columns: [
      { name: "barber", type: "link", link: { table: "barber" } },
      { name: "barbershop", type: "link", link: { table: "barbershop" } },
    ],
  },
  {
    name: "barbershop_preferences",
    columns: [
      { name: "barbershop", type: "link", link: { table: "barbershop" } },
      { name: "prepayment_amount", type: "float", defaultValue: "10" },
      { name: "currency", type: "string", defaultValue: "EUR" },
    ],
  },
  {
    name: "user_preferences",
    columns: [
      { name: "language", type: "string", defaultValue: "en" },
      { name: "hair_type", type: "link", link: { table: "hair_type" } },
      { name: "user", type: "link", link: { table: "nextauth_users" } },
    ],
  },
  {
    name: "barber_skill",
    columns: [
      { name: "skill", type: "link", link: { table: "hair_type" } },
      { name: "barber", type: "link", link: { table: "barber" } },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type NextauthVerificationTokens =
  InferredTypes["nextauth_verificationTokens"];
export type NextauthVerificationTokensRecord = NextauthVerificationTokens &
  XataRecord;

export type NextauthUsers = InferredTypes["nextauth_users"];
export type NextauthUsersRecord = NextauthUsers & XataRecord;

export type Barbershop = InferredTypes["barbershop"];
export type BarbershopRecord = Barbershop & XataRecord;

export type Address = InferredTypes["address"];
export type AddressRecord = Address & XataRecord;

export type FavoriteBarbershop = InferredTypes["favorite_barbershop"];
export type FavoriteBarbershopRecord = FavoriteBarbershop & XataRecord;

export type NextauthAccounts = InferredTypes["nextauth_accounts"];
export type NextauthAccountsRecord = NextauthAccounts & XataRecord;

export type NextauthUsersAccounts = InferredTypes["nextauth_users_accounts"];
export type NextauthUsersAccountsRecord = NextauthUsersAccounts & XataRecord;

export type NextauthUsersSessions = InferredTypes["nextauth_users_sessions"];
export type NextauthUsersSessionsRecord = NextauthUsersSessions & XataRecord;

export type NextauthSessions = InferredTypes["nextauth_sessions"];
export type NextauthSessionsRecord = NextauthSessions & XataRecord;

export type PriceList = InferredTypes["price_list"];
export type PriceListRecord = PriceList & XataRecord;

export type PriceListItem = InferredTypes["price_list_item"];
export type PriceListItemRecord = PriceListItem & XataRecord;

export type OpeningHours = InferredTypes["opening_hours"];
export type OpeningHoursRecord = OpeningHours & XataRecord;

export type Barber = InferredTypes["barber"];
export type BarberRecord = Barber & XataRecord;

export type HairType = InferredTypes["hair_type"];
export type HairTypeRecord = HairType & XataRecord;

export type BarberHairType = InferredTypes["barber_hair_type"];
export type BarberHairTypeRecord = BarberHairType & XataRecord;

export type Reservation = InferredTypes["reservation"];
export type ReservationRecord = Reservation & XataRecord;

export type BarbershopBarberInvitation =
  InferredTypes["barbershop_barber_invitation"];
export type BarbershopBarberInvitationRecord = BarbershopBarberInvitation &
  XataRecord;

export type BarbershopPreferences = InferredTypes["barbershop_preferences"];
export type BarbershopPreferencesRecord = BarbershopPreferences & XataRecord;

export type UserPreferences = InferredTypes["user_preferences"];
export type UserPreferencesRecord = UserPreferences & XataRecord;

export type BarberSkill = InferredTypes["barber_skill"];
export type BarberSkillRecord = BarberSkill & XataRecord;

export type DatabaseSchema = {
  nextauth_verificationTokens: NextauthVerificationTokensRecord;
  nextauth_users: NextauthUsersRecord;
  barbershop: BarbershopRecord;
  address: AddressRecord;
  favorite_barbershop: FavoriteBarbershopRecord;
  nextauth_accounts: NextauthAccountsRecord;
  nextauth_users_accounts: NextauthUsersAccountsRecord;
  nextauth_users_sessions: NextauthUsersSessionsRecord;
  nextauth_sessions: NextauthSessionsRecord;
  price_list: PriceListRecord;
  price_list_item: PriceListItemRecord;
  opening_hours: OpeningHoursRecord;
  barber: BarberRecord;
  hair_type: HairTypeRecord;
  barber_hair_type: BarberHairTypeRecord;
  reservation: ReservationRecord;
  barbershop_barber_invitation: BarbershopBarberInvitationRecord;
  barbershop_preferences: BarbershopPreferencesRecord;
  user_preferences: UserPreferencesRecord;
  barber_skill: BarberSkillRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Talha-Bayansar-s-workspace-l2p3gj.eu-central-1.xata.sh/db/my-barber",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
